kind: ServiceAccount
apiVersion: v1
metadata:
  name: auto-labeller
  namespace: kube-system
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:auto-labeller
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "watch", "update", "get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:auto-labeller
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
subjects:
  - kind: ServiceAccount
    name: auto-labeller
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:auto-labeller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auto-labeller
  name: auto-labeller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auto-labeller
  template:
    metadata:
      labels:
        app: auto-labeller
    spec:
      serviceAccountName: auto-labeller
      containers:
        - image: adaptant/k8s-auto-labeller:latest
          name: auto-labeller
